---
dependency:
  name: galaxy
  options:
    role-file: requirements.yaml
    requirements-file: collections.yaml
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: localhost
provisioner:
  name: ansible
verifier:
  name: ansible