---
- name: Remove all Ghost containers and networks
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:

    - name: Remove containers
      docker_container:
        name: "{{ item }}"
        state: absent
        container_default_behavior: compatibility
      loop:
        - nginx_ghost
        - ghost

    - name: Remove network
      docker_network:
        name: ghostnet
        state: absent