- name: Create ghostdata directory
  file:
    path: "{{ data_dir }}"
    state: directory
    mode: '0750'

- name: Start ghost container
  docker_container:
    name: ghost
    image: ghost
    container_default_behavior: compatibility
    network_mode: host
    networks:
      - name: "{{ net_name }}"
    volumes:
      - "{{ data_dir }}:/var/lib/ghost/content"
    env:
      database__client: mysql
      database__connection__host: "{{ database_host }}"
      database__connection__user: "{{ database_user }}"
      database__connection__password: "{{ database_password }}"
      database__connection__database: "{{ database_name }}"
      url: "https://{{ inventory_hostname }}"
      NODE_ENV: production