---
- hosts: all
  gather_facts: yes
  tasks:
  - name: show IP address
    debug:
      msg: >
        This host uses IP address {{ ansible_facts.default_ipv4.address }} 
  - name: show IP address again
    debug:
      msg: This host uses IP address {{ ansible_facts['default_ipv4']['address'] }}
  - name: lets inject!
    debug:
      msg: This host uses inected variables {{ ansible_default_ipv4.address }}
  - name: and another one
    debug:
      var: ansible_default_ipv4['address']
